site_title: "Léa Guéry-Odelin - Harpiste Professionnelle"
site_description: "Harpiste professionnelle - Concerts, événements, mariages, formations"
contact_email: "bureau@lecresvb.fr"
logo_fr: "/DB/Logo_traductions/fr.webp"
logo_en: "/DB/Logo_traductions/en.png"
logo_de: "/DB/Logo_traductions/de.avif"
